# Generated by Django 5.2.7 on 2026-01-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="email_verified",
            field=models.BooleanField(default=False),
        ),
    ]
