# Generated by Django 5.2.7 on 2026-01-11 15:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0002_client_email_verified"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="email_verified",
        ),
    ]
