# Generated by Django 5.2.7 on 2025-11-24 19:49

import datetime
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("suppliers", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="supplier",
            name="foundation_year",
        ),
        migrations.AddField(
            model_name="supplier",
            name="foundation_date",
            field=models.DateField(
                default=django.utils.timezone.now,
                validators=[
                    django.core.validators.MaxValueValidator(
                        datetime.date(2025, 11, 24)
                    )
                ],
            ),
            preserve_default=False,
        ),
    ]
