# Generated by Django 5.2.7 on 2025-11-23 15:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cars", "0001_initial"),
        ("salons", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=250)),
                ("info", models.JSONField(blank=True, null=True)),
                ("started_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PromotionCar",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cars.car"
                    ),
                ),
                (
                    "promotion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="promotions.promotion",
                    ),
                ),
            ],
            options={
                "unique_together": {("promotion", "car")},
            },
        ),
        migrations.AddField(
            model_name="promotion",
            name="cars",
            field=models.ManyToManyField(
                related_name="car_promotions",
                through="promotions.PromotionCar",
                through_fields=("promotion", "car"),
                to="cars.car",
            ),
        ),
        migrations.CreateModel(
            name="PromotionSalon",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                ("discount", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "promotion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="promotions.promotion",
                    ),
                ),
                (
                    "salon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="salons.salon"
                    ),
                ),
            ],
            options={
                "unique_together": {("promotion", "salon")},
            },
        ),
        migrations.AddField(
            model_name="promotion",
            name="salons",
            field=models.ManyToManyField(
                related_name="salon_promotions",
                through="promotions.PromotionSalon",
                through_fields=("promotion", "salon"),
                to="salons.salon",
            ),
        ),
    ]
