# Generated by Django 5.2.7 on 2025-11-19 20:43

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cars", "0001_initial"),
        ("salons", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Car",
        ),
        migrations.RemoveField(
            model_name="deal",
            name="car",
        ),
        migrations.RemoveField(
            model_name="deal",
            name="client",
        ),
        migrations.RemoveField(
            model_name="deal",
            name="salon",
        ),
        migrations.RemoveField(
            model_name="deal",
            name="supplier",
        ),
        migrations.RemoveField(
            model_name="preference",
            name="client",
        ),
        migrations.RemoveField(
            model_name="promotion",
            name="cars",
        ),
        migrations.RemoveField(
            model_name="promotion",
            name="salons",
        ),
        migrations.AlterUniqueTogether(
            name="promotioncar",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="promotioncar",
            name="car",
        ),
        migrations.RemoveField(
            model_name="promotioncar",
            name="promotion",
        ),
        migrations.AlterUniqueTogether(
            name="promotionsalon",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="promotionsalon",
            name="promotion",
        ),
        migrations.RemoveField(
            model_name="promotionsalon",
            name="salon",
        ),
        migrations.RemoveField(
            model_name="supplier",
            name="cars",
        ),
        migrations.RemoveField(
            model_name="supplier",
            name="user",
        ),
        migrations.AlterUniqueTogether(
            name="suppliercar",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="suppliercar",
            name="car",
        ),
        migrations.RemoveField(
            model_name="suppliercar",
            name="supplier",
        ),
        migrations.RemoveField(
            model_name="saloncar",
            name="number",
        ),
        migrations.AddField(
            model_name="saloncar",
            name="count",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="salon",
            name="balance",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="salon",
            name="cars",
            field=models.ManyToManyField(
                through="salons.SalonCar",
                through_fields=("salon", "car"),
                to="cars.car",
            ),
        ),
        migrations.AlterField(
            model_name="salon",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="saloncar",
            name="car",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cars.car"
            ),
        ),
        migrations.AlterField(
            model_name="saloncar",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="saloncar",
            name="salon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="salons.salon"
            ),
        ),
        migrations.DeleteModel(
            name="Client",
        ),
        migrations.DeleteModel(
            name="Deal",
        ),
        migrations.DeleteModel(
            name="Preference",
        ),
        migrations.DeleteModel(
            name="Promotion",
        ),
        migrations.DeleteModel(
            name="PromotionCar",
        ),
        migrations.DeleteModel(
            name="PromotionSalon",
        ),
        migrations.DeleteModel(
            name="Supplier",
        ),
        migrations.DeleteModel(
            name="SupplierCar",
        ),
    ]
