# Generated by Django 5.2.7 on 2025-11-19 20:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                ("brand", models.CharField(max_length=250)),
                (
                    "model",
                    models.CharField(
                        choices=[
                            ("TOYOTA", "Toyota"),
                            ("HONDA", "Honda"),
                            ("BMW", "BMW"),
                            ("MERCEDES", "Mercedes-Benz"),
                            ("AUDI", "Audi"),
                        ],
                        max_length=25,
                    ),
                ),
                ("characteristic", models.JSONField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
